import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container p-10 mx-auto">
        <header>
          <p className="leading-tight">Abhishek Kalia</p>
          <p className="leading-tight opacity-60">Product Designer</p>
          <p className="leading-tight opacity-60">New York</p>
        </header>

        <div className="mt-10">
          <p>📱 Designer of usable interfaces.</p>
          <p>💻 Developer of full-stack applications.</p>
          <p>🧱 Maintainer of scalable design systems.</p>
          <div className="mt-3">
            <a className="text-blue-700">+ Read More</a>
          </div>
        </div>

        <div className="work mt-20">
          <p className="text uppercase text-sm font-bold mb-10">
            Selected Work
          </p>
          <div className="work-grid grid grid-cols-1 gap-10 md:grid-cols-1 lg:grid-cols-2 xl:grid-cols-3">
            <div className="entry">
              <div className="image w-auto h-72 md:h-96 bg-slate-400 basis-full"></div>
              <div className="description">
                <p className="leading-tight">Guided journaling for Headspace</p>
                <p className="leading-tight opacity-60">
                  Product Design / 2023
                </p>
              </div>
            </div>

            <div className="entry">
              <div className="image w-auto h-72 md:h-96 bg-slate-500 "></div>
              <div className="description">
                <p className="leading-tight">Guided journaling for Headspace</p>
                <p className="leading-tight opacity-60">
                  Product Design / 2023
                </p>
              </div>
            </div>

            <div className="entry">
              <div className="image w-auto h-72 md:h-96 bg-slate-500 basis-full"></div>
              <div className="description">
                <p className="leading-tight">Guided journaling for Headspace</p>
                <p className="leading-tight opacity-60">
                  Product Design / 2023
                </p>
              </div>
            </div>

            <div className="entry">
              <div className="image w-auto h-72 md:h-96 bg-slate-500 basis-full"></div>
              <div className="description">
                <p className="leading-tight">Guided journaling for Headspace</p>
                <p className="leading-tight opacity-60">
                  Product Design / 2023
                </p>
              </div>
            </div>

            <div className="entry">
              <div className="image w-auto h-72 md:h-96 bg-slate-500 basis-full"></div>
              <div className="description">
                <p className="leading-tight">Guided journaling for Headspace</p>
                <p className="leading-tight opacity-60">
                  Product Design / 2023
                </p>
              </div>
            </div>

            <div className="entry">
              <div className="image w-auto h-72 md:h-96 bg-slate-500 basis-full"></div>
              <div className="description">
                <p className="leading-tight">Guided journaling for Headspace</p>
                <p className="leading-tight opacity-60">
                  Product Design / 2023
                </p>
              </div>
            </div>

            <div className="entry">
              <div className="image w-auto h-72 md:h-96 bg-slate-500 basis-full"></div>
              <div className="description">
                <p className="leading-tight">Guided journaling for Headspace</p>
                <p className="leading-tight opacity-60">
                  Product Design / 2023
                </p>
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
