import Entry from "@/components/Entry";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Abhishek Kalia</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="icon"
          href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>💻</text></svg>"
        />
      </Head>
      <main className="container p-5 mx-auto my-10">
        <header>
          <p className="leading-tight font-bold">Abhishek Kalia</p>
          <p className="leading-tight opacity-60">
            Product Designer & Developer
          </p>
          <p className="leading-tight opacity-60">New York</p>
        </header>

        <div className="mt-10">
          <p>📱 Designer of usable interfaces.</p>
          <p>💻 Developer of full-stack applications.</p>
          <p>🧱 Maintainer of scalable design systems.</p>
          <div className="mt-3">
            <a className="text-blue-700">+ More About Me</a>
          </div>
        </div>

        <div className="work mt-20">
          <p className="text uppercase text-sm font-bold mb-10">
            Selected Work
          </p>
          <div className="work-grid grid grid-cols-1 gap-10 md:grid-cols-1 lg:grid-cols-2 xl:grid-cols-3">
            <Entry
              name={"Guided journaling for Headspace"}
              type="Product Design / 2023"
              background="bg-slate-300"
            />
            <Entry
              name={"Guided journaling for Headspace"}
              type="Product Design / 2023"
              background="bg-slate-300"
            />
            <Entry
              name={"Guided journaling for Headspace"}
              type="Product Design / 2023"
              background="bg-slate-300"
            />
            <Entry
              name={"Guided journaling for Headspace"}
              type="Product Design / 2023"
              background="bg-slate-300"
            />
            <Entry
              name={"Guided journaling for Headspace"}
              type="Product Design / 2023"
              background="bg-slate-300"
            />
          </div>
        </div>
      </main>
    </>
  );
}
